scenario: ChatGPT_Operator

baseline_tools:
  - Browser_open
  - Browser_click
  - Browser_type
  - Browser_find
  - page_analyze


llm:
  provider: gemini
  model: gemini-2.0-flash
  api_key_file: API_Key/gemini_api_key

# llm:
#   provider: openai_compat : gemma
#   model: llama3.1
#   base_url: http://localhost:11434/v1/
#   api_key: ollama    

# llm:
#   provider: "ollama"
#   model: "qwen2.5"     # <-- 이렇게 변경 (14b를 받았다면 "qwen2.5:14b")
#   base_url: "http://localhost:11434/v1"
#   api_key: "ollama"

logging:
  base_dir: run/logs

runner:
  max_steps: 6

modes:
  normal:
    paths:
      system_prompt: scenarios/ChatGPT_Operator/system.txt
      tasks: scenarios/ChatGPT_Operator/tasks_benign.jsonl
      tools: scenarios/ChatGPT_Operator/normal_tools.json

  attack:
    paths:
      system_prompt: scenarios/ChatGPT_Operator/system.txt
      tasks: scenarios/ChatGPT_Operator/tasks_attack.jsonl
      tools: scenarios/ChatGPT_Operator/attack_tools.json
